enableGlobalCache: true

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@nestjs/common@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      rxjs: '*'
  '@types/express@*':
    dependencies:
      serve-static: '*'
  '@types/express-serve-static-core@*':
    dependencies:
      send: '*'
      qs: '*'
      range-parser: '*'
  '@types/send@*':
    dependencies:
      mime: '*'
  '@types/serve-static@*':
    dependencies:
      http-errors: '*'

pnpMode: loose

supportedArchitectures:
  cpu:
    - current
  os:
    - current
