import { DataSource } from 'typeorm';
import { Seeder } from '@jorgebodega/typeorm-seeding';
import { Country } from '../../../../location/infrastructure/database/entities/country.entity';

export default class CountriesSeeder extends Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const countryRepository = dataSource.getRepository(Country);

    const countries = [
      {
        name: 'Afganistán',
        iso2: 'AF',
        iso3: 'AFG',
        phoneCode: '93',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Albania',
        iso2: 'AL',
        iso3: 'ALB',
        phoneCode: '355',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Alemania',
        iso2: 'DE',
        iso3: 'DEU',
        phoneCode: '49',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Algeria',
        iso2: 'DZ',
        iso3: 'DZA',
        phoneCode: '213',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Andorra',
        iso2: 'AD',
        iso3: 'AND',
        phoneCode: '376',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Angola',
        iso2: 'AO',
        iso3: 'AGO',
        phoneCode: '244',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Anguila',
        iso2: 'AI',
        iso3: 'AIA',
        phoneCode: '1264',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Antártida',
        iso2: 'AQ',
        iso3: 'ATA',
        phoneCode: '672',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Antigua y Barbuda',
        iso2: 'AG',
        iso3: 'ATG',
        phoneCode: '1268',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Arabia Saudí',
        iso2: 'SA',
        iso3: 'SAU',
        phoneCode: '966',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Argelia',
        iso2: 'DZ',
        iso3: 'DZA',
        phoneCode: '213',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Argentina',
        iso2: 'AR',
        iso3: 'ARG',
        phoneCode: '54',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Armenia',
        iso2: 'AM',
        iso3: 'ARM',
        phoneCode: '374',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Aruba',
        iso2: 'AW',
        iso3: 'ABW',
        phoneCode: '297',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Australia',
        iso2: 'AU',
        iso3: 'AUS',
        phoneCode: '61',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Austria',
        iso2: 'AT',
        iso3: 'AUT',
        phoneCode: '43',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Azerbaiyán',
        iso2: 'AZ',
        iso3: 'AZE',
        phoneCode: '994',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bahamas',
        iso2: 'BS',
        iso3: 'BHS',
        phoneCode: '1242',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bahrein',
        iso2: 'BH',
        iso3: 'BHR',
        phoneCode: '973',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bangladesh',
        iso2: 'BD',
        iso3: 'BGD',
        phoneCode: '880',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Barbados',
        iso2: 'BB',
        iso3: 'BRB',
        phoneCode: '1246',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bielorrusia',
        iso2: 'BY',
        iso3: 'BLR',
        phoneCode: '375',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bélgica',
        iso2: 'BE',
        iso3: 'BEL',
        phoneCode: '32',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Belice',
        iso2: 'BZ',
        iso3: 'BLZ',
        phoneCode: '501',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Benín',
        iso2: 'BJ',
        iso3: 'BEN',
        phoneCode: '229',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bermudas',
        iso2: 'BM',
        iso3: 'BMU',
        phoneCode: '1441',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bhután',
        iso2: 'BT',
        iso3: 'BTN',
        phoneCode: '975',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bolivia',
        iso2: 'BO',
        iso3: 'BOL',
        phoneCode: '591',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bosnia y Herzegovina',
        iso2: 'BA',
        iso3: 'BIH',
        phoneCode: '387',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Botsuana',
        iso2: 'BW',
        iso3: 'BWA',
        phoneCode: '267',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Brasil',
        iso2: 'BR',
        iso3: 'BRA',
        phoneCode: '55',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Brunéi',
        iso2: 'BN',
        iso3: 'BRN',
        phoneCode: '673',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Bulgaria',
        iso2: 'BG',
        iso3: 'BGR',
        phoneCode: '359',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Burkina Faso',
        iso2: 'BF',
        iso3: 'BFA',
        phoneCode: '226',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Burundi',
        iso2: 'BI',
        iso3: 'BDI',
        phoneCode: '257',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Cabo Verde',
        iso2: 'CV',
        iso3: 'CPV',
        phoneCode: '238',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Camboya',
        iso2: 'KH',
        iso3: 'KHM',
        phoneCode: '855',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Camerún',
        iso2: 'CM',
        iso3: 'CMR',
        phoneCode: '237',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Canadá',
        iso2: 'CA',
        iso3: 'CAN',
        phoneCode: '1',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Chad',
        iso2: 'TD',
        iso3: 'TCD',
        phoneCode: '235',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Chile',
        iso2: 'CL',
        iso3: 'CHL',
        phoneCode: '56',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'China',
        iso2: 'CN',
        iso3: 'CHN',
        phoneCode: '86',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Chipre',
        iso2: 'CY',
        iso3: 'CYP',
        phoneCode: '357',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Colombia',
        iso2: 'CO',
        iso3: 'COL',
        phoneCode: '57',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Comoras',
        iso2: 'KM',
        iso3: 'COM',
        phoneCode: '269',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Congo',
        iso2: 'CG',
        iso3: 'COG',
        phoneCode: '242',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Corea del Norte',
        iso2: 'KP',
        iso3: 'PRK',
        phoneCode: '850',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Corea del Sur',
        iso2: 'KR',
        iso3: 'KOR',
        phoneCode: '82',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Costa Rica',
        iso2: 'CR',
        iso3: 'CRI',
        phoneCode: '506',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Costa de Marfil',
        iso2: 'CI',
        iso3: 'CIV',
        phoneCode: '225',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Croacia',
        iso2: 'HR',
        iso3: 'HRV',
        phoneCode: '385',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Cuba',
        iso2: 'CU',
        iso3: 'CUB',
        phoneCode: '53',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Dinamarca',
        iso2: 'DK',
        iso3: 'DNK',
        phoneCode: '45',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Dominica',
        iso2: 'DM',
        iso3: 'DMA',
        phoneCode: '1767',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Ecuador',
        iso2: 'EC',
        iso3: 'ECU',
        phoneCode: '593',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Egipto',
        iso2: 'EG',
        iso3: 'EGY',
        phoneCode: '20',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'El Salvador',
        iso2: 'SV',
        iso3: 'SLV',
        phoneCode: '503',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Emiratos Árabes Unidos',
        iso2: 'AE',
        iso3: 'ARE',
        phoneCode: '971',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Eritrea',
        iso2: 'ER',
        iso3: 'ERI',
        phoneCode: '291',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Eslovaquia',
        iso2: 'SK',
        iso3: 'SVK',
        phoneCode: '421',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Eslovenia',
        iso2: 'SI',
        iso3: 'SVN',
        phoneCode: '386',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'España',
        iso2: 'ES',
        iso3: 'ESP',
        phoneCode: '34',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Estados Unidos',
        iso2: 'US',
        iso3: 'USA',
        phoneCode: '1',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Estonia',
        iso2: 'EE',
        iso3: 'EST',
        phoneCode: '372',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Etiopía',
        iso2: 'ET',
        iso3: 'ETH',
        phoneCode: '251',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Filipinas',
        iso2: 'PH',
        iso3: 'PHL',
        phoneCode: '63',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Finlandia',
        iso2: 'FI',
        iso3: 'FIN',
        phoneCode: '358',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Fiyi',
        iso2: 'FJ',
        iso3: 'FJI',
        phoneCode: '679',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Francia',
        iso2: 'FR',
        iso3: 'FRA',
        phoneCode: '33',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Gabón',
        iso2: 'GA',
        iso3: 'GAB',
        phoneCode: '241',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Gambia',
        iso2: 'GM',
        iso3: 'GMB',
        phoneCode: '220',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Georgia',
        iso2: 'GE',
        iso3: 'GEO',
        phoneCode: '995',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Ghana',
        iso2: 'GH',
        iso3: 'GHA',
        phoneCode: '233',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Gibraltar',
        iso2: 'GI',
        iso3: 'GIB',
        phoneCode: '350',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Granada',
        iso2: 'GD',
        iso3: 'GRD',
        phoneCode: '1473',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Grecia',
        iso2: 'GR',
        iso3: 'GRC',
        phoneCode: '30',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Groenlandia',
        iso2: 'GL',
        iso3: 'GRL',
        phoneCode: '299',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guadalupe',
        iso2: 'GP',
        iso3: 'GLP',
        phoneCode: '590',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guam',
        iso2: 'GU',
        iso3: 'GUM',
        phoneCode: '1671',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guatemala',
        iso2: 'GT',
        iso3: 'GTM',
        phoneCode: '502',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guayana Francesa',
        iso2: 'GF',
        iso3: 'GUF',
        phoneCode: '594',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guernsey',
        iso2: 'GG',
        iso3: 'GGY',
        phoneCode: '441481',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guinea',
        iso2: 'GN',
        iso3: 'GIN',
        phoneCode: '224',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guinea Ecuatorial',
        iso2: 'GQ',
        iso3: 'GNQ',
        phoneCode: '240',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guinea-Bissau',
        iso2: 'GW',
        iso3: 'GNB',
        phoneCode: '245',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Guyana',
        iso2: 'GY',
        iso3: 'GUY',
        phoneCode: '592',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Haití',
        iso2: 'HT',
        iso3: 'HTI',
        phoneCode: '509',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Honduras',
        iso2: 'HN',
        iso3: 'HND',
        phoneCode: '504',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Hong Kong',
        iso2: 'HK',
        iso3: 'HKG',
        phoneCode: '852',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Hungría',
        iso2: 'HU',
        iso3: 'HUN',
        phoneCode: '36',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'India',
        iso2: 'IN',
        iso3: 'IND',
        phoneCode: '91',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Indonesia',
        iso2: 'ID',
        iso3: 'IDN',
        phoneCode: '62',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Irak',
        iso2: 'IQ',
        iso3: 'IRQ',
        phoneCode: '964',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Irán',
        iso2: 'IR',
        iso3: 'IRN',
        phoneCode: '98',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Irlanda',
        iso2: 'IE',
        iso3: 'IRL',
        phoneCode: '353',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Isla Bouvet',
        iso2: 'BV',
        iso3: 'BVT',
        phoneCode: '55',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Isla de Man',
        iso2: 'IM',
        iso3: 'IMN',
        phoneCode: '441624',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Isla de Navidad',
        iso2: 'CX',
        iso3: 'CXR',
        phoneCode: '61',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Isla Norfolk',
        iso2: 'NF',
        iso3: 'NFK',
        phoneCode: '672',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islandia',
        iso2: 'IS',
        iso3: 'ISL',
        phoneCode: '354',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Bermudas',
        iso2: 'BM',
        iso3: 'BMU',
        phoneCode: '1441',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Caimán',
        iso2: 'KY',
        iso3: 'CYM',
        phoneCode: '345',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Cocos',
        iso2: 'CC',
        iso3: 'CCK',
        phoneCode: '61',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Cook',
        iso2: 'CK',
        iso3: 'COK',
        phoneCode: '682',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Feroe',
        iso2: 'FO',
        iso3: 'FRO',
        phoneCode: '298',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Georgias del Sur y Sandwich del Sur',
        iso2: 'GS',
        iso3: 'SGS',
        phoneCode: '500',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Heard y McDonald',
        iso2: 'HM',
        iso3: 'HMD',
        phoneCode: '672',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Malvinas',
        iso2: 'FK',
        iso3: 'FLK',
        phoneCode: '500',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Marianas del Norte',
        iso2: 'MP',
        iso3: 'MNP',
        phoneCode: '1670',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Marshall',
        iso2: 'MH',
        iso3: 'MHL',
        phoneCode: '692',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Pitcairn',
        iso2: 'PN',
        iso3: 'PCN',
        phoneCode: '872',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Salomón',
        iso2: 'SB',
        iso3: 'SLB',
        phoneCode: '677',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Turcas y Caicos',
        iso2: 'TC',
        iso3: 'TCA',
        phoneCode: '1649',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Vírgenes Británicas',
        iso2: 'VG',
        iso3: 'VGB',
        phoneCode: '1284',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Islas Vírgenes de los Estados Unidos',
        iso2: 'VI',
        iso3: 'VIR',
        phoneCode: '1340',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Israel',
        iso2: 'IL',
        iso3: 'ISR',
        phoneCode: '972',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Italia',
        iso2: 'IT',
        iso3: 'ITA',
        phoneCode: '39',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Jamaica',
        iso2: 'JM',
        iso3: 'JAM',
        phoneCode: '1876',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Japón',
        iso2: 'JP',
        iso3: 'JPN',
        phoneCode: '81',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Jersey',
        iso2: 'JE',
        iso3: 'JEY',
        phoneCode: '441534',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Jordania',
        iso2: 'JO',
        iso3: 'JOR',
        phoneCode: '962',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Kazajstán',
        iso2: 'KZ',
        iso3: 'KAZ',
        phoneCode: '7',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Kenia',
        iso2: 'KE',
        iso3: 'KEN',
        phoneCode: '254',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Kirguistán',
        iso2: 'KG',
        iso3: 'KGZ',
        phoneCode: '996',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Kiribati',
        iso2: 'KI',
        iso3: 'KIR',
        phoneCode: '686',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Kuwait',
        iso2: 'KW',
        iso3: 'KWT',
        phoneCode: '965',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Laos',
        iso2: 'LA',
        iso3: 'LAO',
        phoneCode: '856',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Lesoto',
        iso2: 'LS',
        iso3: 'LSO',
        phoneCode: '266',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Letonia',
        iso2: 'LV',
        iso3: 'LVA',
        phoneCode: '371',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Líbano',
        iso2: 'LB',
        iso3: 'LBN',
        phoneCode: '961',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Liberia',
        iso2: 'LR',
        iso3: 'LBR',
        phoneCode: '231',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Libia',
        iso2: 'LY',
        iso3: 'LBY',
        phoneCode: '218',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Liechtenstein',
        iso2: 'LI',
        iso3: 'LIE',
        phoneCode: '423',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Lituania',
        iso2: 'LT',
        iso3: 'LTU',
        phoneCode: '370',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Luxemburgo',
        iso2: 'LU',
        iso3: 'LUX',
        phoneCode: '352',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Macao',
        iso2: 'MO',
        iso3: 'MAC',
        phoneCode: '853',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Madagascar',
        iso2: 'MG',
        iso3: 'MDG',
        phoneCode: '261',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Malasia',
        iso2: 'MY',
        iso3: 'MYS',
        phoneCode: '60',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Malawi',
        iso2: 'MW',
        iso3: 'MWI',
        phoneCode: '265',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Maldivas',
        iso2: 'MV',
        iso3: 'MDV',
        phoneCode: '960',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Malí',
        iso2: 'ML',
        iso3: 'MLI',
        phoneCode: '223',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Malta',
        iso2: 'MT',
        iso3: 'MLT',
        phoneCode: '356',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Marruecos',
        iso2: 'MA',
        iso3: 'MAR',
        phoneCode: '212',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Martinica',
        iso2: 'MQ',
        iso3: 'MTQ',
        phoneCode: '596',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mauricio',
        iso2: 'MU',
        iso3: 'MUS',
        phoneCode: '230',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mauritania',
        iso2: 'MR',
        iso3: 'MRT',
        phoneCode: '222',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mayotte',
        iso2: 'YT',
        iso3: 'MYT',
        phoneCode: '262',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'México',
        iso2: 'MX',
        iso3: 'MEX',
        phoneCode: '52',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Micronesia',
        iso2: 'FM',
        iso3: 'FSM',
        phoneCode: '691',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Moldavia',
        iso2: 'MD',
        iso3: 'MDA',
        phoneCode: '373',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mónaco',
        iso2: 'MC',
        iso3: 'MCO',
        phoneCode: '377',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mongolia',
        iso2: 'MN',
        iso3: 'MNG',
        phoneCode: '976',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Montenegro',
        iso2: 'ME',
        iso3: 'MNE',
        phoneCode: '382',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Montserrat',
        iso2: 'MS',
        iso3: 'MSR',
        phoneCode: '1664',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Mozambique',
        iso2: 'MZ',
        iso3: 'MOZ',
        phoneCode: '258',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Myanmar',
        iso2: 'MM',
        iso3: 'MMR',
        phoneCode: '95',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Namibia',
        iso2: 'NA',
        iso3: 'NAM',
        phoneCode: '264',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nauru',
        iso2: 'NR',
        iso3: 'NRU',
        phoneCode: '674',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nepal',
        iso2: 'NP',
        iso3: 'NPL',
        phoneCode: '977',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nicaragua',
        iso2: 'NI',
        iso3: 'NIC',
        phoneCode: '505',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Níger',
        iso2: 'NE',
        iso3: 'NER',
        phoneCode: '227',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nigeria',
        iso2: 'NG',
        iso3: 'NGA',
        phoneCode: '234',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Niue',
        iso2: 'NU',
        iso3: 'NIU',
        phoneCode: '683',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Noruega',
        iso2: 'NO',
        iso3: 'NOR',
        phoneCode: '47',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nueva Caledonia',
        iso2: 'NC',
        iso3: 'NCL',
        phoneCode: '687',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Nueva Zelanda',
        iso2: 'NZ',
        iso3: 'NZL',
        phoneCode: '64',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Omán',
        iso2: 'OM',
        iso3: 'OMN',
        phoneCode: '968',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Países Bajos',
        iso2: 'NL',
        iso3: 'NLD',
        phoneCode: '31',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Pakistán',
        iso2: 'PK',
        iso3: 'PAK',
        phoneCode: '92',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Palau',
        iso2: 'PW',
        iso3: 'PLW',
        phoneCode: '680',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Palestina',
        iso2: 'PS',
        iso3: 'PSE',
        phoneCode: '970',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Panamá',
        iso2: 'PA',
        iso3: 'PAN',
        phoneCode: '507',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Papúa Nueva Guinea',
        iso2: 'PG',
        iso3: 'PNG',
        phoneCode: '675',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Paraguay',
        iso2: 'PY',
        iso3: 'PRY',
        phoneCode: '595',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Perú',
        iso2: 'PE',
        iso3: 'PER',
        phoneCode: '51',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Polinesia Francesa',
        iso2: 'PF',
        iso3: 'PYF',
        phoneCode: '689',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Polonia',
        iso2: 'PL',
        iso3: 'POL',
        phoneCode: '48',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Portugal',
        iso2: 'PT',
        iso3: 'PRT',
        phoneCode: '351',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Puerto Rico',
        iso2: 'PR',
        iso3: 'PRI',
        phoneCode: '1939',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Qatar',
        iso2: 'QA',
        iso3: 'QAT',
        phoneCode: '974',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Reino Unido',
        iso2: 'GB',
        iso3: 'GBR',
        phoneCode: '44',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'República Centroafricana',
        iso2: 'CF',
        iso3: 'CAF',
        phoneCode: '236',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'República Checa',
        iso2: 'CZ',
        iso3: 'CZE',
        phoneCode: '420',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'República Democrática del Congo',
        iso2: 'CD',
        iso3: 'COD',
        phoneCode: '243',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'República Dominicana',
        iso2: 'DO',
        iso3: 'DOM',
        phoneCode: '1849',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'República de Macedonia',
        iso2: 'MK',
        iso3: 'MKD',
        phoneCode: '389',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Reunión',
        iso2: 'RE',
        iso3: 'REU',
        phoneCode: '262',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Ruanda',
        iso2: 'RW',
        iso3: 'RWA',
        phoneCode: '250',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Rumania',
        iso2: 'RO',
        iso3: 'ROU',
        phoneCode: '40',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Rusia',
        iso2: 'RU',
        iso3: 'RUS',
        phoneCode: '7',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Sahara Occidental',
        iso2: 'EH',
        iso3: 'ESH',
        phoneCode: '212',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Samoa',
        iso2: 'WS',
        iso3: 'WSM',
        phoneCode: '685',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Samoa Americana',
        iso2: 'AS',
        iso3: 'ASM',
        phoneCode: '1684',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Bartolomé',
        iso2: 'BL',
        iso3: 'BLM',
        phoneCode: '590',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Cristóbal y Nieves',
        iso2: 'KN',
        iso3: 'KNA',
        phoneCode: '1869',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Marino',
        iso2: 'SM',
        iso3: 'SMR',
        phoneCode: '378',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Martín',
        iso2: 'MF',
        iso3: 'MAF',
        phoneCode: '590',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Pedro y Miquelón',
        iso2: 'PM',
        iso3: 'SPM',
        phoneCode: '508',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'San Vicente y las Granadinas',
        iso2: 'VC',
        iso3: 'VCT',
        phoneCode: '1784',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Santa Elena',
        iso2: 'SH',
        iso3: 'SHN',
        phoneCode: '290',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Santa Lucía',
        iso2: 'LC',
        iso3: 'LCA',
        phoneCode: '1758',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Santo Tomé y Príncipe',
        iso2: 'ST',
        iso3: 'STP',
        phoneCode: '239',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Senegal',
        iso2: 'SN',
        iso3: 'SEN',
        phoneCode: '221',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Serbia',
        iso2: 'RS',
        iso3: 'SRB',
        phoneCode: '381',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Seychelles',
        iso2: 'SC',
        iso3: 'SYC',
        phoneCode: '248',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Sierra Leona',
        iso2: 'SL',
        iso3: 'SLE',
        phoneCode: '232',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Singapur',
        iso2: 'SG',
        iso3: 'SGP',
        phoneCode: '65',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Siria',
        iso2: 'SY',
        iso3: 'SYR',
        phoneCode: '963',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Somalia',
        iso2: 'SO',
        iso3: 'SOM',
        phoneCode: '252',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Sri Lanka',
        iso2: 'LK',
        iso3: 'LKA',
        phoneCode: '94',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Suazilandia',
        iso2: 'SZ',
        iso3: 'SWZ',
        phoneCode: '268',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Sudáfrica',
        iso2: 'ZA',
        iso3: 'ZAF',
        phoneCode: '27',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Sudán',
        iso2: 'SD',
        iso3: 'SDN',
        phoneCode: '249',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Suecia',
        iso2: 'SE',
        iso3: 'SWE',
        phoneCode: '46',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Suiza',
        iso2: 'CH',
        iso3: 'CHE',
        phoneCode: '41',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Surinam',
        iso2: 'SR',
        iso3: 'SUR',
        phoneCode: '597',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Svalbard y Jan Mayen',
        iso2: 'SJ',
        iso3: 'SJM',
        phoneCode: '47',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tailandia',
        iso2: 'TH',
        iso3: 'THA',
        phoneCode: '66',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tanzania',
        iso2: 'TZ',
        iso3: 'TZA',
        phoneCode: '255',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tayikistán',
        iso2: 'TJ',
        iso3: 'TJK',
        phoneCode: '992',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Territorio Británico del Océano Índico',
        iso2: 'IO',
        iso3: 'IOT',
        phoneCode: '246',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Territorios Australes Franceses',
        iso2: 'TF',
        iso3: 'ATF',
        phoneCode: '262',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Timor Oriental',
        iso2: 'TL',
        iso3: 'TLS',
        phoneCode: '670',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Togo',
        iso2: 'TG',
        iso3: 'TGO',
        phoneCode: '228',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tokelau',
        iso2: 'TK',
        iso3: 'TKL',
        phoneCode: '690',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tonga',
        iso2: 'TO',
        iso3: 'TON',
        phoneCode: '676',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Trinidad y Tobago',
        iso2: 'TT',
        iso3: 'TTO',
        phoneCode: '1868',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Túnez',
        iso2: 'TN',
        iso3: 'TUN',
        phoneCode: '216',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Turkmenistán',
        iso2: 'TM',
        iso3: 'TKM',
        phoneCode: '993',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Turquía',
        iso2: 'TR',
        iso3: 'TUR',
        phoneCode: '90',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Tuvalu',
        iso2: 'TV',
        iso3: 'TUV',
        phoneCode: '688',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Ucrania',
        iso2: 'UA',
        iso3: 'UKR',
        phoneCode: '380',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Uganda',
        iso2: 'UG',
        iso3: 'UGA',
        phoneCode: '256',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Uruguay',
        iso2: 'UY',
        iso3: 'URY',
        phoneCode: '598',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Uzbekistán',
        iso2: 'UZ',
        iso3: 'UZB',
        phoneCode: '998',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Vanuatu',
        iso2: 'VU',
        iso3: 'VUT',
        phoneCode: '678',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Venezuela',
        iso2: 'VE',
        iso3: 'VEN',
        phoneCode: '58',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Vietnam',
        iso2: 'VN',
        iso3: 'VNM',
        phoneCode: '84',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Wallis y Futuna',
        iso2: 'WF',
        iso3: 'WLF',
        phoneCode: '681',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Yemen',
        iso2: 'YE',
        iso3: 'YEM',
        phoneCode: '967',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Yibuti',
        iso2: 'DJ',
        iso3: 'DJI',
        phoneCode: '253',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Zambia',
        iso2: 'ZM',
        iso3: 'ZMB',
        phoneCode: '260',
        createdBy: '1',
        updatedBy: '1',
      },
      {
        name: 'Zimbabue',
        iso2: 'ZW',
        iso3: 'ZWE',
        phoneCode: '263',
        createdBy: '1',
        updatedBy: '1',
      },
    ];

    await countryRepository.save(countries);
  }
}
